@Carden.Api_HostAddress = http://localhost:5209

GET {{Carden.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{Carden.Api_HostAddress}}/api/v1/auth/register
Content-Type: application/json

{
  "email": "cmdliner@gmail.com",
  "full_name": "Abdulazeez Abiade",
  "username": "Commandliner",
  "password": "testpassword&123"
}


###
POST https://{{Carden.Api_HostAddress}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "cmdliner@gmail.com",
  "password": "testpassword&123"
}

###
POST https://{{Carden.Api_HostAddress}}/api/v1/auth/refresh
Content-Type: application/json
Authorization: Bearer {{Carden.Auth.Access_Token}}
Cookie: {{Carden.Auth.Refresh_Cookie}}

### Add new expense item
POST https://{{Carden.Api_HostAddress}}/api/v1/expense-items/
Content-Type: application/json
Authorization: Bearer {{Carden.Auth.Access_Token}}
Cookie: {{Carden.Auth.Refresh_Cookie}}

{
  "name": "Loafers",
  "expected_price": 40000,
  "category": "clothing"
}

### Get single expense item
GET https://{{Carden.Api_HostAddress}}/api/v1/expense-items/0198931f-6fd6-7fce-8d2d-43031a142ebc
Content-Type: application/json
Authorization: Bearer {{Carden.Auth.Access_Token}}
Cookie: {{Carden.Auth.Refresh_Cookie}}

### Get all expense items
GET https://{{Carden.Api_HostAddress}}/api/v1/expense-items/
Content-Type: application/json
Authorization: Bearer {{Carden.Auth.Access_Token}}
Cookie: {{Carden.Auth.Refresh_Cookie}}

### Update item priority
PUT https://{{Carden.Api_HostAddress}}/api/v1/expense-items/01989326-a9f1-75b3-855f-fc633f679b1b/priority
Content-Type: application/json
Authorization: Bearer {{Carden.Auth.Access_Token}}
Cookie: {{Carden.Auth.Refresh_Cookie}}

{
  "priority": 3
}

###
DELETE https://{{Carden.Api_HostAddress}}/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer {{Carden.Auth.Access_Token}}
Cookie: {{Carden.Auth.Refresh_Cookie}}

###
GET https://{{Carden.Api_HostAddress}}/api/v1/users
Accept: application/json
Authorization: Bearer {{Carden.Auth.Access_Token}}
Cookie:  {{Carden.Auth.Refresh_Cookie}}